
title: Shangrong Yang


#sidebar links
email: sr_yang@bjtu.edu.cn
#phone: 012 345 6789
#linkedin: alandoe
website_zhihu: ZHIHU
website_csdn: CSDN
website_google: Google Scholar
website_semantic: Semantic Scholar
github: Github
port: 4001
#Update all the sections by editing the files inside _includes folder.
